[29기 최희택] 카카오 로그인 진행 중
wecode-bootcamp-korea/29-2nd-DSNB-backend pull request #13
Opened 2022-02-17 01:59 UTC by sosolyht

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)

- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)

- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-02-18 08:36 UTC, jamessoun93 requested changes

2022-02-18 08:36 UTC, jamessoun93 commented on users/tests.py
> +        headers             = {"Authoriazation": "가짜 access_token"}
```suggestion
        headers             = {"Authorization": "가짜 access_token"}
```

2022-02-18 08:36 UTC, jamessoun93 commented on users/tests.py
> +        access_token        = jwt.encode({'user_id' : 1}, settings.SECRET_KEY, settings.ALGORITHM)
여기에는 만료날짜 설정이 안되어있네요~

2022-02-18 09:13 UTC, sosolyht commented on users/tests.py
> +        headers             = {"Authoriazation": "가짜 access_token"}
오타 수정하였습니다!

2022-02-18 09:13 UTC, sosolyht commented on users/tests.py
> +        access_token        = jwt.encode({'user_id' : 1}, settings.SECRET_KEY, settings.ALGORITHM)
설정완료하였습니다.

2022-02-21 05:18 UTC, jamessoun93 approved these changes

2022-02-21 05:18 UTC, merged